### ISSUE TITLE
Question regarding the future of the component

### ISSUE THREAD

**Issue by theprobugmaker** [RonaldJerez/vue-the-mask#6]
Do you plan to keep updating the component? I need to use in a very important project but it seems that `vue-the-mask` is abandoned by it's creator so I wanted to know if you really want to continue his work.

**Comment by RonaldJerez** [comment]
Hello,  the original has been abandoned which is why I started this fork.  I plan on keeping this one as updated as possible. I am too using it in a production project so expect it to be updated frequently.

I am currently working on a big rewrite (see v1 Branch).  This will bring it up to date with latest vue version as well as fix some outstanding issues.

**Comment by theprobugmaker** [comment]
@RonaldJerez Thank you for the answer. If I might be honest with you, as you are rewriting the project somehow, you might as well give it another name and just mention the creator on the readme instead of trying to resurrect it by the fork. It will call more attention for people to use.

**Comment by RonaldJerez** [comment]
@zefexdeveloper Yes I have considered that.  I reached out to Neves to see if he would transfer ownership of the NPM package. When I complete the rewrite if he hasn’t responded then I will likely publish it under a new name.

**Comment by theprobugmaker** [comment]
@RonaldJerez Nice, I'm looking forward to that. Right now I'm currently creating the forms without the masking cause most of the components aren't working properly so I will add a new one later when I find.

**Comment by RonaldJerez** [comment]
@zefexdeveloper i have released the new component vue-input-facade

https://github.com/RonaldJerez/vue-input-facade

**Comment by RonaldJerez** [comment]
Hey @zefexdeveloper, I have released [vue-input-facade](https://github.com/ronaldjerez/vue-input-facade)

Try it out and see if it meets your needs.

**Comment by theprobugmaker** [comment]
@RonaldJerez Thank you for remembering me and yes it does. I will be using and perhaps sending a few suggestions as well. Keep up the good work.
